#ifndef HMIEVENTS_H
#define HMIEVENTS_H
namespace HMIEvents {
    
typedef enum HMIEventsTag{
    ADD_NEW_BOOK_SELECT,
    ADD_NEW_BOOK_CONFIRM,
    ADD_NEW_MEMBER_SELECT,
    ADD_NEW_MEMBER_SELECT_CONFIRM,
    REMOVE_MEMBER_SELECT,
    REMOVE_MEMBER_SELECT_CONFIRM,
    REMOVE_BOOK_SELECT,
    REMOVE_BOOK_SELECT_CONFIRM,
    ISSUE_RETURN_BOOK_SELECT,
    RETURN_BOOK_SELECT_CONFIRM,
    ISSUE_BOOK_SELECT_CONFIRM,
    QUERY_BOOK_SELECT,
    QUERY_BOOK_SELECT_CONFIRM,
    HMI_UPDATE_BOOK_QUERY_LIST,
    PREVIOUS_SCREEN
}HMIEvents_t;

};







#endif
