#ifndef HMISCREENS_H
#define HMISCREENS_H

namespace HMISCREENS{

typedef enum  HMIScreensTag{
   HOME_SCREEN,
   ADDNEWBOOK_SCREEN,
   REMOVEBOOK_SCREEN,
   ADDMEMBER_SCREEN,
   ISSUERETURNBOOK_SCREEN,
   REMOVEMEMBER_SCREEN,
   QUERYBOOK_SCREEN
}HMIScreens_t;

};

#endif
